version: "3.8"
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: myapp
      MYSQL_ROOT_PASSWORD: password
      # MYSQL_USER: root
      # MYSQL_PASSWORD: youruserpassword
      # Uncomment the line below if you face authentication issues
      # MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db:
